/* Generated by miscs/tef/tools/gen_assets.py — DO NOT EDIT. */
#include "tef_assets.h"

const tef_asset_t g_tef_assets[] = {
    { "neutral", g_tef_neutral, 15865u },
    { "annoyed", g_tef_annoyed, 79294u },
    { "cool", g_tef_cool, 70154u },
    { "fearful", g_tef_fearful, 139197u },
    { "happy", g_tef_happy, 23844u },
    { "lovestruck", g_tef_lovestruck, 196655u },
    { "sad", g_tef_sad, 67912u },
    { "stat_connecting", g_tef_stat_connecting, 983u },
    { "stat_initializing", g_tef_stat_initializing, 5874u },
    { "stat_listening", g_tef_stat_listening, 614u },
    { "stat_provisioning", g_tef_stat_provisioning, 2530u },
    { "stat_speaking", g_tef_stat_speaking, 1127u },
    { "stat_thinking", g_tef_stat_thinking, 605u },
    { "stat_uploading", g_tef_stat_uploading, 1300u },
    { "stat_waiting", g_tef_stat_waiting, 997u },
    { "surprise", g_tef_surprise, 69089u },
    { "thinking", g_tef_thinking, 115981u },
};

const uint32_t g_tef_asset_cnt = sizeof(g_tef_assets) / sizeof(g_tef_assets[0]);
