#!/usr/bin/env python3
"""
TEF 素材批量生成器 —— 一键把一个目录的 GIF 编成固件用 C 数组 + 注册表。

用法（默认就地一键）:
  cd src/miscs/tef/tools
  mkdir gif && cp <你的素材>/*.gif gif/     # 文件名即素材名(如 neutral.gif)
  python3 gen_assets.py                     # 输出到 ./out/

指定目录（板级素材维护，如 EYES）:
  python3 gen_assets.py <gif_dir> <out_dir>
  # 例: python3 src/miscs/tef/tools/gen_assets.py \\
  #         src/boards/T5AI_BOARD_EYES/ui/eyes_tef/gif \\
  #         src/boards/T5AI_BOARD_EYES/ui/eyes_tef

可选参数:
  --stabilize auto|8|16|24|32   时域整形前处理，抑制 AI 生成/抖动量化素材的
                                帧间噪声（默认关闭；边界与原理见 tef_encoder.py）

输出（<out_dir>/）:
  tef_<name>.c        每个 GIF 一个数组 g_tef_<name>[]（.tef 字节流）
  tef_assets.h        声明 + 注册表类型 tef_asset_t
  tef_assets.c        注册表 g_tef_assets[] / g_tef_asset_cnt

约定:
  - 素材名 = GIF 文件名（不含扩展名，需为合法 C 标识符）；用作表情名时须与
    云端 emoji 名一致（见 src/wukong/skills/skill_emotion.c）。
  - 注册表把 "neutral"（若存在）排在第 0 项，其余按字母序——播放侧未命中
    名字时回落表 0。
  - 编码禁用 JPEG 帧（设备端解码器不带 JPEG）；成段帧数 SEG=16（嵌入式解压
    缓冲上界与之线性相关，改动需评估 tef_player 的 PSRAM 占用）。

依赖: Pillow, numpy。原理与格式规范见 ../docs/TEF_技术规范.html，
桌面预览/校验工具见同目录 tef_player.py / tef_decoder.py。
"""
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tef_encoder import encode_gif, STAB_LEVELS  # noqa: E402

SEG = 16          # 成段帧数
JPEG_Q = 0        # 禁用 JPEG 帧


def emit_c_array(name: str, data: bytes, out: Path):
    lines = [
        "/* Generated by miscs/tef/tools/gen_assets.py — DO NOT EDIT.",
        f" * TEF asset '{name}', {len(data)} bytes. */",
        "#include <stdint.h>",
        "",
        f"const uint8_t g_tef_{name}[{len(data)}] = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"const uint32_t g_tef_{name}_len = {len(data)};")
    lines.append("")
    out.write_text("\n".join(lines))


def main():
    here = Path(__file__).resolve().parent
    args = sys.argv[1:]
    stabilize = None
    if "--stabilize" in args:
        i = args.index("--stabilize")
        if i + 1 >= len(args):
            sys.exit("--stabilize 需要参数: auto|8|16|24|32")
        stabilize = args[i + 1]
        if stabilize not in ("auto",) + tuple(str(t) for t in STAB_LEVELS):
            sys.exit("--stabilize 取值须为: auto|8|16|24|32")
        del args[i:i + 2]
    gif_dir = Path(args[0]) if len(args) > 0 else here / "gif"
    out_dir = Path(args[1]) if len(args) > 1 else here / "out"

    gifs = sorted(gif_dir.glob("*.gif"), key=lambda p: p.stem.lower())
    if not gifs:
        sys.exit(f"no .gif found in {gif_dir}")
    # neutral（回落项）置于表 0
    gifs.sort(key=lambda p: (p.stem.lower() != "neutral", p.stem.lower()))
    for g in gifs:
        if not g.stem.isidentifier():
            sys.exit(f"{g.name}: 文件名须为合法 C 标识符（用作符号 g_tef_<name>）")
    out_dir.mkdir(parents=True, exist_ok=True)

    stats_all = []
    for src in gifs:
        name = src.stem
        with tempfile.NamedTemporaryFile(suffix=".tef") as tt:
            st = encode_gif(str(src), tt.name, seg=SEG, jpeg_q=JPEG_Q, verbose=False,
                            stabilize=stabilize)
            tef = Path(tt.name).read_bytes()
        emit_c_array(name, tef, out_dir / f"tef_{name}.c")
        stats_all.append((name, len(tef)))
        stab = f" stab[{st['stabilize']}]" if stabilize else ""
        print(f"{name:13s} {st['W']}x{st['H']} {st['N']:3d}帧 fps={st['fps']:2d} "
              f"{st['ncolors']:3d}色/{st['index_bits']}bit tile={st['tile']:2d} "
              f"gif={src.stat().st_size:7,d}B -> tef={st['size']:7,d}B "
              f"(jpeg帧={st['jpeg_frames']}){stab}")

    hdr = [
        "/* Generated by miscs/tef/tools/gen_assets.py — DO NOT EDIT. */",
        "#ifndef __TEF_ASSETS_H__",
        "#define __TEF_ASSETS_H__",
        "",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "typedef struct {",
        "    const char    *name;   /* 素材名(表情场景须与云端 emoji 字段一致) */",
        "    const uint8_t *data;   /* .tef 字节流 */",
        "    uint32_t       len;",
        "} tef_asset_t;",
        "",
        "extern const tef_asset_t g_tef_assets[];   /* 第 0 项为回落素材 */",
        "extern const uint32_t g_tef_asset_cnt;",
        "",
    ]
    for name, _ in stats_all:
        hdr.append(f"extern const uint8_t g_tef_{name}[];")
        hdr.append(f"extern const uint32_t g_tef_{name}_len;")
    hdr += ["", "#ifdef __cplusplus", "}", "#endif", "",
            "#endif /* __TEF_ASSETS_H__ */", ""]
    (out_dir / "tef_assets.h").write_text("\n".join(hdr))

    src_lines = [
        "/* Generated by miscs/tef/tools/gen_assets.py — DO NOT EDIT. */",
        '#include "tef_assets.h"',
        "",
        "const tef_asset_t g_tef_assets[] = {",
    ]
    for name, tef_len in stats_all:
        src_lines.append(f'    {{ "{name}", g_tef_{name}, {tef_len}u }},')
    src_lines += ["};", "",
                  "const uint32_t g_tef_asset_cnt = "
                  "sizeof(g_tef_assets) / sizeof(g_tef_assets[0]);", ""]
    (out_dir / "tef_assets.c").write_text("\n".join(src_lines))

    total = sum(n for _, n in stats_all)
    print(f"\n共 {len(stats_all)} 个素材, tef 合计 {total:,} 字节 -> {out_dir}")


if __name__ == "__main__":
    main()
