/*
tuya_app_config.h
Copyright(C),2018-2020, 涂鸦科技 www.tuya.comm
*/

/* AUTO-GENERATED FILE. DO NOT MODIFY !!!
*
* This config file is automatically generated by tuya cross-build system.
* It should not be modified by hand.
*/

#ifndef TUYA_APP_CONFIG_H
#define TUYA_APP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define TUYA_MODULE_T5 1
#define ENABLE_DEFAULT_SESSION 1
// CONFIG_T5AI_BOARD is not set
#define T5AI_BOARD_EYES 1
// CONFIG_T5AI_BOARD_EVB is not set
// CONFIG_T5AI_BOARD_EVB_PRO is not set
// CONFIG_T5AI_BOARD_ROBOT is not set
// CONFIG_T5AI_BOARD_DESKTOP is not set
// CONFIG_T2AI_BOARD is not set
// CONFIG_LE270AI_BOARD is not set
// CONFIG_L511_Y6E_BOARD is not set
// CONFIG_L511_Y7PM_BOARD is not set
// CONFIG_T1AI_BOARD is not set
// CONFIG_T3AI_BOARD is not set
// CONFIG_T3_V_PRO_BOARD is not set
// CONFIG_RTL8720CF_VU2_BOARD is not set
// CONFIG_WUKONG_BOARD_UBUNTU is not set
// CONFIG_WUKONG_BOARD_QEMU_M33 is not set

//
// Pin Configuration
//
#define TUYA_AI_TOY_AUDIO_TRIGGER_PIN_NUM 9
#define TUYA_AI_TOY_SPK_EN_PIN_NUM 48
#define TUYA_AI_TOY_LED_PIN_NUM 64
#define TUYA_AI_TOY_NET_PIN_NUM 64
// CONFIG_DEVICE_POWER_CONTROL is not set
// end of Pin Configuration

// CONFIG_ENABLE_TUYA_DISPLAY is not set

//
// AI Mode Configuration
//

//
// Enabled AI Mode
//
// CONFIG_ENABLE_AI_MODE_HOLD is not set
// CONFIG_ENABLE_AI_MODE_ONESHOT is not set
// CONFIG_ENABLE_AI_MODE_WAKEUP is not set
#define ENABLE_AI_MODE_FREE 1
// CONFIG_ENABLE_AI_MODE_TRANSLATE is not set
// CONFIG_ENABLE_AI_MODE_P2P is not set
// CONFIG_ENABLE_AI_MODE_RECORD is not set
// CONFIG_ENABLE_AI_MODE_PICTURE is not set
// end of Enabled AI Mode

#define AI_CHAT_DEFAULT_FREE 1
#define TUYA_AI_CHAT_DEFAULT_MODE 3

//
// AI Agent Solution Code
//
#define AI_AGENT_SCODE_PRESET_DEFAULT 1
// CONFIG_AI_AGENT_SCODE_PRESET_MULTIMODE is not set
// CONFIG_AI_AGENT_SCODE_PRESET_CUSTOM is not set
#define AI_AGENT_SCODE_CHAT ""
#define AI_AGENT_SCODE_TRANSLATE "asr-llm-tts"
#define AI_AGENT_SCODE_PICTURE ""
#define AI_AGENT_SCODE_DETECTION ""

//
// Chat mode scode:        ""
//

//
// Translate mode scode:   "asr-llm-tts"
//

//
// Picture mode scode:     ""
//

//
// Detection mode scode:   ""
//
// end of AI Agent Solution Code
// end of AI Mode Configuration

// CONFIG_ENABLE_BATTERY is not set
// CONFIG_ENABLE_TUYA_CAMERA is not set
#define ENABLE_TUYA_TOOLKITS 1
// CONFIG_ENABLE_TOOLKITS_TM is not set
// CONFIG_ENABLE_TOOLKITS_CONTROL is not set
// CONFIG_ENABLE_TOOLKITS_SYSTEM is not set
// CONFIG_ENABLE_TOOLKITS_SKILL is not set
// CONFIG_ENABLE_TOOLKITS_MEMORY is not set
#define ENABLE_TOOLKITS_PLAYBACK 1
// CONFIG_ENABLE_TOOLKITS_IMM is not set
// CONFIG_ENABLE_TOOLKITS_SOCIAL is not set

//
// Audio Configuration
//

//
// Audio Input
//

//
// --- Source ---
//
// CONFIG_USING_UART_AUDIO_INPUT is not set
#define USING_BOARD_AUDIO_INPUT 1
#define INPUT_BOARD_STACK_SIZE 2560

//
// --- Frontend ---
//
#define USING_TUYA_AUDIO_FRONTEND 1
// CONFIG_USING_SPRS_AUDIO_FRONTEND is not set
// CONFIG_USING_3RD_AUDIO_FRONTEND is not set

//
// --- Encoder ---
//
#define ENABLE_APP_OPUS_ENCODER 1
// CONFIG_ENABLE_APP_SPEEX_ENCODER is not set
#define APP_OPUS_ENCODER_BITRATE 16000
// CONFIG_APP_OPUS_ENCODER_VBR_ENABLE is not set
#define APP_OPUS_ENCODER_BANDWIDTH 1102
// end of Audio Input

//
// Audio Output
//

//
// --- Target ---
//
// CONFIG_USING_UART_AUDIO_OUTPUT is not set
#define USING_BOARD_AUDIO_OUTPUT 1
// end of Audio Output

//
// Audio Player
//

//
// --- Mode ---
//
// CONFIG_AI_PLAYER_LITE is not set

//
// --- Decoders (MP3/WAV always built-in) ---
//
#define AI_PLAYER_DECODER_OPUS_ENABLE 1
#define AI_PLAYER_DECODER_OPUS_FRAME_SIZE 40
#define AI_PLAYER_DECODER_OPUS_KBPS 16
#define AI_PLAYER_DECODER_OGGOPUS_ENABLE 1
// CONFIG_AI_PLAYER_DECODER_OPUS_VBR_ENABLE is not set

//
// --- RAM / Buffers ---
//
#define AI_PLAYER_STACK_SIZE 12288
#define AI_PLAYER_FRAMEBUF_SIZE 4096
#define AI_PLAYER_DECODEBUF_SIZE 9600
#define AI_PLAYER_RINGBUF_SIZE 16384

//
// --- Streaming pre-buffer ---
//
#define AI_PLAYER_MEM_PREBUF_BYTES 2048
#define AI_PLAYER_MEM_PREBUF_TIMEOUT_MS 500

//
// --- URL datasink (HTTP) ---
//
#define AI_PLAYER_HTTP_YIELD_MS 10
#define AI_PLAYER_HTTP_TIMEOUT_S 180

//
// --- Features / Debug ---
//
#define AI_PLAYER_SUPPORT_MIX_MODE 1
#define AI_PLAYER_SUPPORT_RESAMPLE 1
#define AI_PLAYER_SUPPORT_DIGITAL_VOLUME 1
// CONFIG_AI_PLAYER_SUPPORT_DEFAULT_CONSUMER is not set
// CONFIG_AI_PLAYER_DEBUG_STATS is not set
// end of Audio Player

// CONFIG_ENABLE_WUKONG_AUDIO_PIPELINE is not set
// CONFIG_CODEC_BENCH_TEST is not set
// end of Audio Configuration

//
// Video Configuration
//
#define USING_NONE_VIDEO_INPUT 1
// end of Video Configuration

//
// Storage Configuration
//
// CONFIG_WUKONG_STORAGE_SDCARD is not set
// CONFIG_WUKONG_STORAGE_EXT_FLASH is not set
#define WUKONG_STORAGE_NONE 1
// end of Storage Configuration

#define ENABLE_PROVIDER_TUYA 1
// CONFIG_ENABLE_PROVIDER_JD is not set
// CONFIG_ENABLE_PROVIDER_CUBE is not set
// CONFIG_ENABLE_PROVIDER_CLAW is not set

//
// IM Channels
//
// CONFIG_ENABLE_CHAN_WECHAT is not set
// CONFIG_ENABLE_CHAN_FEISHU is not set
// end of IM Channels

//
// Device Defaults
//
#define TY_SPK_DEFAULT_VOL 90
#define TY_AI_DEFAULT_LANG 1
// CONFIG_ENABLE_AUDIO_ANALYSIS is not set
// CONFIG_ENABLE_APP_AI_MONITOR is not set
#define ENABLE_CLOUD_ALERT 1
#define ENABLE_AI_MF_TEST 1
// CONFIG_ENABLE_LOW_POWER is not set
// CONFIG_ENABLE_CLI_TEXT_INPUT is not set
// CONFIG_ENABLE_APP_KV_CACHE is not set
// CONFIG_ENABLE_TUYA_NFC is not set
// CONFIG_ENABLE_CELLULAR_DONGLE is not set
// end of Device Defaults

#ifdef __cplusplus
}
#endif

#endif
