/* Generated by miscs/tef/tools/gen_assets.py — DO NOT EDIT. */
#include "tef_assets.h"

const tef_asset_t g_tef_assets[] = {
    { "neutral", g_tef_neutral, 34530u },
    { "angry", g_tef_angry, 36021u },
    { "confused", g_tef_confused, 23068u },
    { "disappointed", g_tef_disappointed, 35772u },
    { "fearful", g_tef_fearful, 39937u },
    { "happy", g_tef_happy, 29915u },
    { "sad", g_tef_sad, 79882u },
    { "surprise", g_tef_surprise, 33697u },
    { "thinking", g_tef_thinking, 55833u },
    { "touched", g_tef_touched, 50271u },
};

const uint32_t g_tef_asset_cnt = sizeof(g_tef_assets) / sizeof(g_tef_assets[0]);
