/* Generated by miscs/tef/tools/gen_assets.py — DO NOT EDIT. */
#ifndef __TEF_ASSETS_H__
#define __TEF_ASSETS_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char    *name;   /* 素材名(表情场景须与云端 emoji 字段一致) */
    const uint8_t *data;   /* .tef 字节流 */
    uint32_t       len;
} tef_asset_t;

extern const tef_asset_t g_tef_assets[];   /* 第 0 项为回落素材 */
extern const uint32_t g_tef_asset_cnt;

extern const uint8_t g_tef_neutral[];
extern const uint32_t g_tef_neutral_len;
extern const uint8_t g_tef_angry[];
extern const uint32_t g_tef_angry_len;
extern const uint8_t g_tef_confused[];
extern const uint32_t g_tef_confused_len;
extern const uint8_t g_tef_disappointed[];
extern const uint32_t g_tef_disappointed_len;
extern const uint8_t g_tef_fearful[];
extern const uint32_t g_tef_fearful_len;
extern const uint8_t g_tef_happy[];
extern const uint32_t g_tef_happy_len;
extern const uint8_t g_tef_sad[];
extern const uint32_t g_tef_sad_len;
extern const uint8_t g_tef_surprise[];
extern const uint32_t g_tef_surprise_len;
extern const uint8_t g_tef_thinking[];
extern const uint32_t g_tef_thinking_len;
extern const uint8_t g_tef_touched[];
extern const uint32_t g_tef_touched_len;

#ifdef __cplusplus
}
#endif

#endif /* __TEF_ASSETS_H__ */
